---
title: "Rice production Analytics"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
setwd("~/Documents/projects/riceData/jan_revise")
rice <- read.csv("riceData_2019.csv")
area <- read.csv("thai_eng_province.csv")
```

KPI
=====================================  

Row
-----------------------------------------------------------------------

### Total prvinces {.value-box}
```{r}
renderValueBox({
  valueBox(
    value = length(unique(area$Province_name_thai)),
    icon = "fa-area-chart",
    color = "primary"
  )
})
```

### Total Regions {.value-box}
```{r}
renderValueBox({
  valueBox(
    value = length(unique(area$Region)),
    icon = "fa-area-chart",
    color = "primary"
  )
})
```


### Total Zones {.value-box}
```{r}
renderValueBox({
  valueBox(
    value = length(unique(area$Zone)),
    icon = "fa-area-chart",
    color = "primary"
  )
})
```



Page 2
=====================================  
Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
selectInput("n_breaks", label = "Number of bins:",
            choices = c(10, 20, 35, 50), selected = 20)

sliderInput("bw_adjust", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

Page 2
=====================================  